### PR TITLE
update neon, switch to n-api

### PR DESCRIPTION
**Pull request by petabyteboy**
Rust part builds, JS wrapper still needs to be adjusted.

Related:
https://github.com/matrix-org/seshat/issues/94
https://github.com/NixOS/nixpkgs/pull/124907

### CODE REVIEW

**Comment by poljar** [comment]
How does the js wrapper need to be adjusted? The tests at least seem to pass and we do have pure js tests as well.

**Comment by petabyteboy** [comment]
Oh, even better. I think previously it did export whole "classes", while now it only exports functions, which have the kind of object they are expected to run on as a name prefix.
I expected an additional JS class wrapping the Rust functions to be necessary to get the same JS interface.

Also someone should have another look at all the `cx.argument(X)` calls, since the functions now take the `this` object as first parameter instead of retrieving it from the call context.

Are we sure the tests actually cover the creation of a Seshat and SeshatRecovery object and running things on it?

**Comment by poljar** [comment]
> Previously it exported whole "classes", while now it only exports functions, which have the kind of object they are expected to run on as a name prefix.

You don't export the whole class, but you do export methods that are bound to the class, no? At least that's what I'm guessing is going on over [here](https://github.com/matrix-org/seshat/pull/95/files#diff-43ded14acea1ac6bcfd0c8b69462f3fea7f6e21bb7eeb21bf938a136cd3a6ef7R778). I should read the migration guide instead of guessing what's going on :sweat_smile:.

> Also someone should have another look at all the `cx.argument(X)` calls, since the functions now take the `this` object as first parameter instead of retrieving it from the call context.
> 
> Are we sure the tests actually cover the creation of a Seshat and SeshatRecovery object and running things on it?

We do have such tests: https://github.com/matrix-org/seshat/blob/master/seshat-node/test/test.js#L624

**Comment by petabyteboy** [comment]
> You don't export the whole class, but you do export methods that are bound to the class, no?

Yeah, no, there is no "class" in the Rust part anymore. It's just functions that take a Seshat/SeshatRecovery JsBox as first parameter.

Anyways, I think you ran the tests in the root dir of the repo, or maybe you didn't rebuild the native bindings before running the tests? For they are failing, but I'm working on it now.

**Comment by poljar** [comment]
> > You don't export the whole class, but you do export methods that are bound to the class, no?
> 
> Yeah, no, there is no "class" in the Rust part anymore. It's just functions that take a Seshat/SeshatRecovery JsBox as first parameter.
> 
> Anyways, I think you ran the tests in the root dir of the repo, or maybe you didn't rebuild the native bindings before running the tests? For they are failing, but I'm working on it now.

Ah ok, I'll need to fix CI as well since it also claims that everything is fine.

**Comment by petabyteboy** [comment]
I have fixed the remaining tests

**Comment by petabyteboy** [comment]
When used with element-desktop, the module gets loaded, but I can't enable indexing:

screenshot2

It just gets stuck there.

**Comment by poljar** [comment]
Interestingly it does seem to work for me, I did double check that it picked up the local build. It correctly loads the existing database and I can do a disable/enable cycle as well. 

Are there any errors in the terminal or in the logs?

**Comment by petabyteboy** [comment]
Nope, no errors. Did you build the matrix-seshat module in the element-desktop tree with hak or elsewhere?

**Comment by poljar** [comment]
> Nope, no errors. Did you build the matrix-seshat module in the element-desktop tree with hak or elsewhere?

I built the module in the Seshat repo using `yarn install` and used `yarn link` to link it from the element-desktop tree. Usually that method didn't work unless the node versions matched or you would have to specify the node version but with this PR it should just work.

**Comment by petabyteboy** [comment]
Okay, I will have to test some more later and figure out when it works and when it doesn't

**Comment by davidmehren** [comment]
Hi all!
I tried this branch just now and can confirm that it works with Electron 13.1.3 and also loads the old database.

**Comment by petabyteboy** [comment]
Let's merge then? My problems seem to be related to the way I linked it into the electron app.

**Comment by davidmehren** [comment]
For the record, I built it this way:
- Clone the `element-desktop` repo
- Change the electron version in `package.json` to `13.1.3`
- Remove `matrix-seshat` from the `hakDependencies` field in `package.json`
- Run `yarn install`, `yarn run fetch --noverify --cfgdir ''` and `yarn build:native`, which will build keytar.
- Clone and build this branch somewhere
- Copy the `lib` folder, `native/index.node` and `package.json` from the `seshat-node` directory to `element-desktop/.hak/hakModules/matrix-seshat/`, so it looks like this:
```
.hak/hakModules/matrix-seshat/
├── lib
│   └── index.js
├── native
│   └── index.node
└── package.json
```
- Finally run `node_modules/.bin/electron-builder -l dir`, which will create a `dist/linux-unpacked` folder, from which you can run Element.

**Comment by poljar** [comment]
Thanks for testing this. I'll take another look over PR later in the week and merge if everything is fine.

In the worst case it seems that we'll have to modify the build in the element-desktop repo, but that's obviously out of scope for this PR.

**Pull request merged**
